# Generated by Django 6.0.3 on 2026-04-04 14:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_teacherassignment'),
        ('fees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentfeepayment',
            name='academic_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='academics.academicsession'),
        ),
        migrations.AddField(
            model_name='studentfeepayment',
            name='fee_structure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='fees.feestructure'),
        ),
    ]
