# Generated by Django 6.0.3 on 2026-03-26 19:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('people', '0001_initial'),
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('certificate_type', models.CharField(choices=[('LEAVING', 'School Leaving Certificate'), ('MERIT', 'Merit Certificate')], max_length=20)),
                ('file', models.FileField(upload_to='certificates/%Y/%m/')),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_related', to='schools.school')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people.studentprofile')),
            ],
            options={
                'abstract': False,
                'indexes': [models.Index(fields=['school'], name='certificate_school__238ce1_idx')],
            },
        ),
    ]
