# Generated by Django 6.0.3 on 2026-03-28 19:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_type', models.CharField(choices=[('LEAVING', 'School Leaving Certificate'), ('MERIT', 'Merit Certificate')], max_length=20)),
                ('file', models.FileField(upload_to='certificates/%Y/%m/')),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people.studentprofile')),
            ],
        ),
    ]
