# Generated by Django 6.0.3 on 2026-04-12 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0002_remove_studentprofile_user_studentprofile_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherprofile',
            name='registered_device_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
