# Generated by Django 6.0.3 on 2026-04-15 12:12

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0002_teacherassignment'),
        ('people', '0003_teacherprofile_registered_device_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=50)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('slot_type', models.CharField(choices=[('PERIOD', 'Academic Period'), ('BREAK', 'Break/Recess'), ('ASSEMBLY', 'Assembly'), ('OTHER', 'Other')], default='PERIOD', max_length=20)),
                ('order', models.PositiveSmallIntegerField(default=1)),
            ],
            options={
                'ordering': ['order', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='TimingPreset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='WorkdayOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('is_working', models.BooleanField(default=True)),
                ('description', models.CharField(blank=True, help_text='e.g. Working Saturday or Unexpected Holiday', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='AttendanceExtension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField()),
                ('duration_minutes', models.PositiveIntegerField(help_text='Selected via Admin badges (15, 30, 60)')),
                ('is_approved', models.BooleanField(default=False)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.section')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people.teacherprofile')),
            ],
        ),
        migrations.CreateModel(
            name='TimetableEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('MONDAY', 'Monday'), ('TUESDAY', 'Tuesday'), ('WEDNESDAY', 'Wednesday'), ('THURSDAY', 'Thursday'), ('FRIDAY', 'Friday'), ('SATURDAY', 'Saturday'), ('SUNDAY', 'Sunday')], max_length=10)),
                ('room', models.CharField(blank=True, max_length=50, null=True)),
                ('is_attendance_period', models.BooleanField(default=False)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_entries', to='academics.teacherassignment')),
                ('timeslot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='timetable.timeslot')),
            ],
            options={
                'unique_together': {('day', 'timeslot', 'assignment')},
            },
        ),
        migrations.CreateModel(
            name='Substitution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('substitute_teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people.teacherprofile')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='substitutions', to='timetable.timetableentry')),
            ],
        ),
        migrations.AddField(
            model_name='timeslot',
            name='preset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='timetable.timingpreset'),
        ),
    ]
