# Generated by Django 6.0.3 on 2026-03-26 19:53

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(help_text='Unique identifier for the school', unique=True)),
                ('address', models.TextField()),
                ('contact_email', models.EmailField(max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('trial_ends_at', models.DateTimeField(default=datetime.datetime(2026, 3, 28, 19, 53, 22, 306786, tzinfo=datetime.timezone.utc), help_text='Trial period ends after 2 days by default')),
                ('subscription_plan', models.CharField(choices=[('trial', 'Trial'), ('basic', 'Basic Plan'), ('standard', 'Standard Plan'), ('premium', 'Premium Plan')], default='trial', max_length=50)),
                ('subscription_start_date', models.DateField(blank=True, null=True)),
                ('subscription_end_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'School',
                'verbose_name_plural': 'Schools',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SchoolSubscriptionPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount paid in PKR or chosen currency', max_digits=10)),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('transaction_id', models.CharField(help_text='Payment gateway transaction ID (e.g., Stripe, JazzCash, EasyPaisa)', max_length=100, unique=True)),
                ('payment_method', models.CharField(blank=True, choices=[('stripe', 'Stripe'), ('jazzcash', 'JazzCash'), ('easypaisa', 'EasyPaisa'), ('bank_transfer', 'Bank Transfer'), ('other', 'Other')], max_length=50)),
                ('expiry_date', models.DateField(help_text='Subscription expiry date after this payment')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='completed', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_payments', to='schools.school')),
            ],
            options={
                'verbose_name': 'School Subscription Payment',
                'verbose_name_plural': 'School Subscription Payments',
                'ordering': ['-payment_date'],
                'indexes': [models.Index(fields=['school', 'payment_date'], name='schools_sch_school__2d35ad_idx'), models.Index(fields=['transaction_id'], name='schools_sch_transac_949310_idx')],
            },
        ),
    ]
