# Generated by Django 6.0.3 on 2026-04-01 14:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='trial_ends_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 4, 3, 14, 8, 11, 775358, tzinfo=datetime.timezone.utc), help_text='Trial ends after 2 days'),
        ),
    ]
