# Generated by Django 6.0.3 on 2026-04-04 14:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0002_alter_school_trial_ends_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='trial_ends_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 4, 6, 14, 46, 55, 786018, tzinfo=datetime.timezone.utc), help_text='Trial ends after 2 days'),
        ),
    ]
