# Generated by Django 6.0.3 on 2026-04-11 17:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0003_alter_school_trial_ends_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='about_text',
            field=models.TextField(blank=True, help_text="Detailed 'About Us' description."),
        ),
        migrations.AddField(
            model_name='school',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='school_logos/'),
        ),
        migrations.AddField(
            model_name='school',
            name='mission',
            field=models.TextField(blank=True, help_text="School's mission statement."),
        ),
        migrations.AddField(
            model_name='school',
            name='tagline',
            field=models.CharField(blank=True, help_text='A short, catchy phrase about the school.', max_length=255),
        ),
        migrations.AddField(
            model_name='school',
            name='vision',
            field=models.TextField(blank=True, help_text="School's vision statement."),
        ),
        migrations.AlterField(
            model_name='school',
            name='trial_ends_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 4, 13, 17, 14, 0, 24773, tzinfo=datetime.timezone.utc), help_text='Trial ends after 2 days'),
        ),
    ]
