# Generated by Django 6.0.3 on 2026-04-11 18:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0004_school_about_text_school_logo_school_mission_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='trial_ends_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 4, 13, 18, 4, 0, 488557, tzinfo=datetime.timezone.utc), help_text='Trial ends after 2 days'),
        ),
    ]
