# Generated by Django 6.0.3 on 2026-04-15 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_teacherassignment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='class_level',
        ),
        migrations.AddField(
            model_name='subject',
            name='class_levels',
            field=models.ManyToManyField(related_name='subjects', to='academics.classlevel'),
        ),
    ]
