# Generated by Django 6.0.3 on 2026-04-12 14:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
        ('people', '0003_teacherprofile_registered_device_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField(default='07:30:00')),
                ('end_time', models.TimeField(default='08:15:00')),
                ('allowed_ip_network', models.CharField(default='192.168.1.0/24', help_text='CIDR notation, e.g. 192.168.1.0/24', max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Attendance Settings',
            },
        ),
        migrations.AddField(
            model_name='teacherattendance',
            name='device_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='teacherattendance',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teacherattendance',
            name='time_marked',
            field=models.TimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='teacherattendance',
            name='verified_by_otp',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='TeacherAttendanceOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('is_used', models.BooleanField(default=False)),
                ('request_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people.teacherprofile')),
            ],
        ),
    ]
